memgraph:
  uri: bolt://localhost:7687
  username: ""
  password: ""

# E2B Code Interpreter configuration
e2b:
  api:
    key: ${E2B_API_KEY:}

# Piston Code Executor configuration
piston:
  api:
    url: ${PISTON_API_URL:http://localhost:2000}

improved:
  graph:
    enabled: true
app:
  # Embedding model configuration
  embeddings:
    model-type: all-minilm-l6-v2 #onnx or all-minilm-l6-v2 supported
    # For custom ONNX models
    # onnx-model-path: /path/to/model_quantized.onnx
    # tokenizer-path: /path/to/tokenizer.json
    # pooling-mode: mean
  
  # Vector store configuration
  vector-store:
    # Provider to use: in-memory or qdrant
    provider: in-memory
    # Text chunking configuration
    chunk-size: 1000
    chunk-overlap: 200
    
    # Qdrant configuration (used when provider is 'qdrant')
    qdrant:
      host: localhost
      port: 6334
      use-tls: false
      collection-name: masaic-documents
      min-score: 0.0
